"""
Send Paper Monitor HTML digest email.

Required environment variables:
MAIL_USERNAME
MAIL_PASSWORD
MAIL_TO

The program:
- skips sending when there are no new papers;
- reads the current email HTML filename from latest_email.json;
- uses the personalized subject generated by generate_email.py;
- avoids accidentally sending an old HTML digest.
"""

import os
import json
import smtplib
from pathlib import Path
from email.message import EmailMessage
from email.utils import formataddr


ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "web"

NEW_PAPERS_FILE = WEB / "new_papers.json"
LATEST_EMAIL_FILE = WEB / "latest_email.json"


# =========================================================
# Load JSON helper
# =========================================================

def load_json(path, default):

    if not path.exists():
        return default

    with open(
        path,
        "r",
        encoding="utf-8"
    ) as f:

        return json.load(f)


# =========================================================
# Check whether there are new papers
# =========================================================

new_papers = load_json(
    NEW_PAPERS_FILE,
    []
)

if not new_papers:

    print(
        "No new papers. Skip sending email."
    )

    raise SystemExit(0)


# =========================================================
# Read information generated by generate_email.py
# =========================================================

latest_email_info = load_json(
    LATEST_EMAIL_FILE,
    {}
)


html_filename = latest_email_info.get(
    "html_file",
    ""
)


subject = latest_email_info.get(
    "subject",
    "[Paper Monitor] Daily New Papers"
)


# =========================================================
# Check email metadata
# =========================================================

if not html_filename:

    print(
        "No current email HTML information found."
    )

    print(
        "Please run generate_email.py first."
    )

    raise SystemExit(0)


HTML_FILE = WEB / html_filename


# =========================================================
# Check HTML file
# =========================================================

if not HTML_FILE.exists():

    print(
        f"Email HTML not found: {HTML_FILE}"
    )

    print(
        "Skip sending."
    )

    raise SystemExit(0)


# =========================================================
# Read environment variables
# =========================================================

username = os.getenv(
    "MAIL_USERNAME"
)

password = os.getenv(
    "MAIL_PASSWORD"
)

receiver = os.getenv(
    "MAIL_TO"
)


if not username or not password or not receiver:

    raise RuntimeError(
        "Missing MAIL_USERNAME, "
        "MAIL_PASSWORD or MAIL_TO"
    )


# =========================================================
# Read HTML
# =========================================================

html = HTML_FILE.read_text(
    encoding="utf-8"
)


# =========================================================
# Create email
# =========================================================

msg = EmailMessage()


# Personalized subject generated by generate_email.py
msg["Subject"] = subject


msg["From"] = formataddr(
    ("Paper Monitor", username)
)


msg["To"] = receiver


msg.set_content(
    "Please view this email in HTML format."
)


msg.add_alternative(
    html,
    subtype="html"
)


# =========================================================
# Send email
# =========================================================

with smtplib.SMTP_SSL(
    "smtp.gmail.com",
    465
) as smtp:

    smtp.login(
        username,
        password
    )

    smtp.send_message(
        msg
    )


# =========================================================
# Output
# =========================================================

print(
    "Email sent successfully."
)

print(
    f"Subject: {subject}"
)

print(
    f"HTML: {HTML_FILE.name}"
)