name: Auto Update Publication List
on:
  push:
    paths:
      - 'MyPublication.xlsx' # 只有当这个文件更新时才运行
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas openpyxl

      - name: Run Converter
        run: python convert.py # 运行转换脚本生成 papers.json

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add papers.json
          git commit -m "Update papers.json from Excel" || exit 0
          git push